# Generated by Django 4.2 on 2023-04-12 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.province')),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('info', models.TextField()),
                ('StartDate', models.DateTimeField(auto_now_add=True)),
                ('UpdateDate', models.DateTimeField(auto_now=True)),
                ('budget', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Privacy', models.BooleanField()),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.province')),
                ('subprovince', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.subprovince')),
            ],
        ),
    ]
