# Generated by Django 4.2 on 2023-05-03 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pump',
            name='Privacy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pump',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectapp.province'),
        ),
        migrations.AlterField(
            model_name='pump',
            name='subprovince',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectapp.subprovince'),
        ),
    ]
