# Generated by Django 4.2 on 2023-05-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_alter_pump_privacy_alter_pump_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='phone',
            field=models.CharField(default=1, max_length=13, verbose_name='+998** *** ** **'),
            preserve_default=False,
        ),
    ]
