# Generated by Django 4.2 on 2023-05-06 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_alter_pump_phone_alter_pump_province_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='names',
        ),
    ]
