# Generated by Django 4.2 on 2023-05-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pump',
            name='phone',
            field=models.CharField(max_length=2, verbose_name='Tel nomer kiriting'),
        ),
    ]
