# Generated by Django 4.2 on 2023-05-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_alter_pump_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pump',
            name='name',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='pump',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Tel nomer kiriting'),
        ),
    ]
