# Generated by Django 4.2 on 2023-05-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0008_alter_pump_name_alter_pump_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pump',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
