# Generated by Django 4.2 on 2023-05-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0012_alter_pump_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pump',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/media/'),
        ),
    ]
