# Generated by Django 4.2 on 2023-05-09 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0014_alter_pump_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pump',
            name='image',
        ),
    ]
