# Generated by Django 4.2 on 2023-05-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0015_remove_pump_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
