# Generated by Django 4.2.1 on 2023-05-11 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0017_remove_pump_privacy_remove_pump_budget_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pump',
            old_name='yil_mal',
            new_name='umumiy_mal',
        ),
    ]
