# Generated by Django 4.2 on 2023-05-11 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0018_rename_yil_mal_pump_umumiy_mal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pump',
            name='umumiy_mal',
        ),
    ]
