# Generated by Django 4.2 on 2023-05-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0019_remove_pump_umumiy_mal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='umumiy_mal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
